### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by SMiles02** [ubc-123/Lily-forces#1]
Hey there, I saw this and I was really impressed! Is it usable on Windows? Also, I can't seem to see the problem_id of a problem, even after inspecting element. Could you help? My email is slennon.5569@gmail.com , could we discuss there? Thank you so much!

**Comment by ubc-123** [comment]
It works on Linux system. Can be used on Windows using Linux subsystem for Windows.

**Comment by ubc-123** [comment]
![image](https://user-images.githubusercontent.com/46437647/82389815-b73a3200-9a5a-11ea-88c4-af19ee6a6e5d.png)
